// SPDX-License-Identifier: Apache-2.0
// SPDXVersion: SPDX-2.2
// SPDX-FileCopyrightText: Copyright 2020 FreightTrust and Clearing Corporation
:doctype: book

....

Notice: CCPA - CALIFORNIA PRIVACY ACT
License: CC-BY-2.5
Author: Freight Trust & Clearing Corp
Issued: November 25th, 2019
Link: github.com/freight-trust/legal/src.CCPA.adoc
....


= CALIFORNIA RESIDENTS PRIVACY RIGHTS NOTICE

* In Short: Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.

*California Civil Code Section 1798.83*, also known as the _"`Shine The Light`"_ law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year.
If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.

----
email: admin@freighttrust.com
subject: CCPA Request
body: first, last name, user name or public account number, registered e-mail address, and any other related information.
----

If you are under 18 years of age, reside in California, and have a registered account with the Services or Apps, you have the right to request removal of unwanted data that you publicly post on the Services or Apps.

_NOTICE_: We do *NOT* provide services to any persons under the age of 18 in any jurisdiction, if you are below the age of 18, please contact us as soon as possible.

To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California.
We will make sure the data is not publicly displayed on the Services or Apps, but please be aware that the data may not be completely or comprehensively removed from our systems.

==  + Freight Trust & Clearing Corporation.
All Rights Reserved
