= Document Retention Policy

[NAMES OF RELEVANT STATES AND COUNTRIES]
Freight Trust
[and its subsidiaries]
[EMPLOYEE NAME]
[and]
[OTHER DEPARTMENT NAME]
[the Legal Department]

[[contact-person]]
Records Management Officer

== Overivew

The corporate information of Freight Trust [and its subsidiaries] is important to how it conducts business and manages employees.

Federal [and state] law require[s] Freight Trust to retain certain records, usually for a specific amount of time. The accidental or intentional destruction of these records during their specified retention periods could result in the following consequences for Freight Trust and/or its employees:


- Fines and penalties.
- Loss of rights.
- Obstruction of justice charges.
- Inference of spoliation of evidence and spoliation tort claims.
- Contempt of court charges
- Serious disadvantages in litigation.

Freight Trust must retain certain records because they contain information that:

- Serves as Freight Trust's corporate memory.
Has enduring business value (for example, it provides a record of a business transaction, evidences Freight Trust's rights or obligations, protects Freight Trust's legal interests or ensures operational continuity).

- Must be kept to satisfy legal, accounting, or other regulatory requirements.


Freight Trust prohibits the inappropriate destruction of any records, files, documents, samples, and other forms of information. This policy is in accordance with the Sarbanes-Oxley Act of 2002, under which it is a crime to change, conceal, falsify, or destroy any record with the intent to impede or obstruct any official or government proceeding. Therefore, this policy is part of a company-wide system for the review, retention, and destruction of records Freight Trust creates or receives in connection with the business it conducts.


## REASONS FOR POLICY

Counsel may consider revising the clause above to include mention of any state or local law for the jurisdiction(s) where this policy will be used. Also consider adding examples of records that are specific to the company's industry and workplace.

### Types of Documents

This policy explains the differences among records, disposable information, and confidential information belonging to others.

Records A record is any type of information created, received, or transmitted in the transaction of Freight Trust's business, regardless of physical format. Examples of where the various types of information are located include:

- Appointment books and calendars.
- Audio and video recordings.
- Computer programs.
- Contracts.
- Electronic files.
- Emails.
- Handwritten notes.
- Invoices.
- Letters and other correspondence.
- Magnetic tape.
- Memory in cell phones and PDAs.
- Online postings, such as on Facebook, Twitter, Instagram, Medium, Slack, Github and other social media platforms and websites.
- Performance reviews.
- Test samples.
- Voicemails.

Therefore, any paper records and electronic files, including any records of donations made online, that are part of any of the categories listed in the Records Retention Schedule contained in the Appendix to this policy, must be retained for the amount of time indicated in the Records Retention Schedule. A record must not be retained beyond the period indicated in the Record Retention Schedule, unless a valid business reason (or a litigation hold or other special situation) calls for its continued retention. If you are unsure whether to retain a certain record, contact the Records Management Officer or the Legal Department.

#### Disposable Information
Disposable information consists of data that may be discarded or deleted at the discretion of the user once it has served its temporary useful purpose and/or data that may be safely destroyed because it is not a record as defined by this policy. Examples may include:
image

- Duplicates of originals that have not been annotated.
- Preliminary drafts of letters, memoranda, reports, worksheets, and informal notes that do not represent significant steps or decisions in the preparation of an official record.
- Books, periodicals, manuals, training binders, and other printed materials obtained from sources outside of Freight Trust and retained primarily for reference purposes.
- Spam and junk mail.



#### Confidential Information Belonging to Others
Any confidential information that an employee may have obtained from a source outside of Freight Trust, such as a previous employer, must not, so long as such information remains confidential, be disclosed to or used by Freight Trust. Unsolicited confidential information submitted to Freight Trust should be refused, returned to the sender where possible, and deleted, if received via the internet.
Mandatory Compliance


#### Responsibility of All Employees

Freight Trust strives to comply with the laws, rules, and regulations that govern it and with recognized compliance practices. All company employees must comply with this policy, the Records Retention Schedule and any litigation hold communications. Failure to do so may subject Freight Trust, its employees, and contract staff to serious civil and/or criminal liability. An employee's failure to comply with this policy may result in disciplinary sanctions, including suspension or termination.
Reporting Policy Violations Freight Trust is committed to enforcing this policy as it applies to all forms of records. The effectiveness of Freight Trust's efforts, however, depends largely on employees. If you feel that you or someone else may have violated this policy, you should report the incident immediately to your supervisor.

If you are not comfortable bringing the matter up with your immediate supervisor, or do not believe the supervisor has dealt with the matter properly, you should raise the matter with the [Records Management Officer/manager at the next level above your direct supervisor]. If employees do not report inappropriate conduct, Freight Trust may not become aware of a possible violation of this policy and may not be able to take appropriate corrective action. No one will be subject to and Freight Trust prohibits, any form of discipline, reprisal, intimidation, or retaliation for reporting incidents of inappropriate conduct of any kind, pursuing any record destruction claim, or cooperating in related investigations.


## MANDATORY COMPLIANCE
It is important to remind all employees that retaliation of any kind, including for reporting any type of violation of a policy, is strictly prohibited. For more information on retaliation generally and how to prevent it, see Practice Note, Retaliation.


### Records Management Department and Records Management Officer

The Records Management Department is responsible for identifying the documents that Freight Trust must or should retain, and determining, in collaboration with the Legal Department, the proper period of retention. It also arranges for the proper storage and retrieval of records, coordinating with outside vendors where appropriate. Additionally, the Records Management Department handles the destruction of records whose retention period has expired.

Freight Trust has designated [EMPLOYEE NAME] as the Records Management Officer. The Records Management Officer is head of the Records Management Department and is responsible for:

- Administering the document management program and helping department heads implement it and related best practices.
- Planning, developing, and prescribing document disposal policies, systems, standards, and procedures.
- Writing straightforward document management procedures to instruct employees on how to comply with this policy.
- Monitoring departmental compliance so that employees know how to follow the document management procedures and the Legal Department has confidence that Freight Trust's records are controlled.
- Ensuring that senior management is aware of their departments' document management responsibilities.

Developing and implementing measures to ensure that the Legal Department knows what information Freight Trust has and where it is stored, that only authorized users have access to the information, and that Freight Trust keeps only the information it needs, thereby efficiently using space.

- Establishing standards for filing and storage equipment and recordkeeping supplies.

In cooperation with department heads, identifying essential records and establishing a disaster plan for each office and department to ensure maximum availability of Freight Trust's records in order to reestablish operations quickly and with minimal interruption and expense.

- Developing procedures to ensure the permanent preservation of Freight Trust's historically valuable records.

- Providing document management advice and assistance to all departments by preparing manuals of procedure and policy and by on-site consultation.

- Determining the practicability of and, if appropriate, establishing a uniform filing system and a forms design and control system.

Periodically reviewing the records retention schedules and administrative rules issued by the governments of [NAMES OF RELEVANT STATES AND COUNTRIES] to determine if Freight Trust's document management program and its Records Retention Schedule is in compliance with state [and foreign] regulations.


- Distributing to the various department heads information concerning state laws and administrative rules relating to corporate records.

- Explaining to employees their duties relating to the document management program.

- Ensuring that the maintenance, preservation, microfilming, computer disk storage, destruction, or other disposition of Freight Trust's records is carried out in accordance with this policy, the procedures of the document management program and the requirements of federal and state law.

- Planning the timetable for the annual records destruction exercise and the annual records audit, including setting deadlines for responses from departmental staff.

- Maintaining records on the volume of records destroyed under the Records Retention Schedule and the records stored electronically.

- Evaluating the overall effectiveness of the document management program.

* Reporting annually to the Legal Department [and] [OTHER DEPARTMENT NAME] on the implementation of the document management program in each of Freight Trust's departments.

* Bringing to the attention of the Legal Department any noncompliance by department heads or other employees with this policy and Freight Trust's document management program.


## RECORDS MANAGEMENT DEPARTMENT AND RECORDS MANAGEMENT OFFICER

For more information on the roles within the company that are responsible for implementing and managing the policy, see Practice Note, Drafting a Document Retention Policy: Define Employees' DRP Roles and Responsibilities.

## How to Store and Destroy Records


Storage Freight Trust's records must be stored in a safe, secure, and accessible manner. Any documents and financial files that are essential to Freight Trust's business operations during an emergency must be duplicated and/or backed up at least once per week and maintained off site.


## STORAGE

This clause reminds employees to back up files necessary for the company's business continuation procedures. Counsel should consider revising the clause to include any records protected by state or local law for the jurisdiction(s) where this policy will be used. Also consider indicating the off-site location where duplicate files must be sent if physical copies are to be stored in a separate location, such as a storage facility.

Destruction Freight Trust's [Records Management Officer/OTHER OFFICER/MANAGER] is responsible for the continuing process of identifying the records that have met their required retention period and supervising their destruction. The destruction of confidential, financial, and personnel-related records must be conducted by shredding if possible. Non-confidential records may be destroyed by recycling. The destruction of electronic records must be coordinated with the IT Department [TITLE].
The destruction of records must stop immediately upon notification from [the Legal Department] that a litigation hold is to begin because Freight Trust may be involved in a lawsuit or an official investigation (see next paragraph). Destruction may begin again once the Legal Department lifts the relevant litigation hold.

=== Destruction

The dcument management program and training procedures include instructions on how the Records Management Officer and other employees should destroy records. Once an employee destroys a record, he should document its destruction with the Records Management Officer, the Legal Department and other relevant personnel. The destruction of electronic records should be coordinated with the IT department to ensure that all copies of the electronic records are discarded, including copies residing on backup tapes, temporary files, additional servers, and all employees' email in-boxes and other electronic storage locations.


## Litigation Holds and Other Special Situations

Freight Trust requires all employees to comply fully with its published records retention schedule and procedures as provided in this policy. All employees should note the following general exception to any stated destruction schedule: If you believe, or [the Legal Department] informs you, that Freight Trust records are relevant to current litigation, potential litigation (that is, a dispute that could result in litigation), government investigation, audit, or other event, you must preserve and not delete, dispose, destroy, or change those records, including emails, until [the Legal Department] determines those records are no longer needed. This exception is referred to as a litigation hold or legal hold, replaces any previously or subsequently established destruction schedule for those records. If you believe this exception may apply, or have any questions regarding whether it may possibly apply, please contact [the Legal Department].
